### ISSUE TITLE
Request/Suggestion: Velocity support

### ISSUE THREAD

**Issue by mteij** [DenizenScript/DepenizenBungee#4]
PaperMC recently adapted the [Velocity](https://velocitypowered.com/) proxy software project and intends to deprecate Waterfall. As a result, Velocity is going to rise in popularity and Velocity might even become the new standard. Therefore, I hope that consideration will be given to making a velocity version of DepenizenBungee, which in my opinion is a very useful addition to the denizen scripting system.

**Comment by mcmonkey4eva** [comment]
Velocity is not Bungee.

Denizen and related projects have support on Discord @ https://discord.gg/Q6pZGSR
